export const products = [
    {id: "0", img: "sony_ps5.webp", title: 'Sony PlayStation 5', price: 56990, description: "Память: 1TB SSD \nМаксимальное разрешение 8К\nС дисководом", category: "Все"},
    {id: "1", img: "ip15promax_titanium.webp", title: 'Iphone 15 Pro Max Natural Titanuim', price: 114990, description: "Экран 120 Гц \nПроцессор: A17 Pro \nПамять: 256 Гб \nType-C", category: "Телефоны"},
    {id: "2", img: "ip15pro_titanium.webp", title: 'Iphone 15 Pro Natural Titanium', price: 106990, description: "Экран 120 Гц \nПроцессор: A17 Pro \nПамять: 256 Гб \nType-C", category: "Телефоны"},
    {id: "3", img: "ip15_pro_black_titanium.webp", title: 'Iphone 15 Pro Black Titanium', price: 106990, description: "Экран 120 Гц \nПроцессор: A17 Pro \nПамять: 256 Гб \nType-C", category: "Телефоны"},
    {id: "4", img: "ip15_black.webp", title: 'Iphone 15 Black', price: 89990, description: "Экран 60 Гц \nПроцессор: A16 Bionic \nПамять: 256 Гб", category: "Телефоны"},
    {id: "5", img: "ip15_black.webp", title: 'Iphone 15 Black', price: 75990, description: "Экран 60 Гц \nПроцессор: A16 Bionic \nПамять: 128 Гб", category: "Телефоны"},
    {id: "6", img: "ip14_starlight.webp", title: 'Iphone 14 Starlight', price: 69990, description: "Dual Nano SIM\nПроцессор: A15 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "7", img: "ip14_white.webp", title: 'Iphone 14 White', price: 69990, description: "Dual Nano SIM\nПроцессор: A15 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "8", img: "ip14_purple.webp", title: 'Iphone 14 Purple', price: 69990, description: "Dual Nano SIM\nПроцессор: A15 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "9", img: "ip14_midnight.webp", title: 'Iphone 14 Midnight', price: 69990, description: "Dual Nano SIM\nПроцессор: A15 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "10", img: "ip13_midnight.webp", title: 'Iphone 13 Midnight', price: 68990, description: "Dual Nano SIM\nПроцессор: A15 Bionic\nПамять: 256 Гб", category: "Телефоны"},
    {id: "11", img: "ip13_midnight.webp", title: 'Iphone 13 Midnight', price: 59990, description: "Dual Nano SIM\nПроцессор: A15 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "12", img: "ip11_white.webp", title: 'Iphone 11 Black', price: 44990, description: "Dual Nano SIM\nПроцессор: A13 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "13", img: "ip11_black.webp", title: 'Iphone 11 Black', price: 44990, description: "Dual Nano SIM\nПроцессор: A13 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "14", img: "ipse_midnight.webp", title: 'Iphone SE Midnight', price: 49990, description: "nanoSIM + eSIM\nПроцессор: A15 Bionic\nПамять: 128 Гб", category: "Телефоны"},
    {id: "31", img: "7.webp", title: 'Samsung Galaxy A55 Black', price: 43990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "32", img: "8.webp", title: 'Samsung Galaxy A25 Black', price: 25990, description: "ОЗУ: 6 Гб \nПамять: 128 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "33", img: "9.webp", title: 'Samsung Galaxy A15 Dark Blue', price: 17990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "34", img: "10.webp", title: 'Samsung Galaxy A15 Dark Blue', price: 13990, description: "ОЗУ: 4 Гб \nПамять: 128 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "35", img: "11.webp", title: 'Samsung Galaxy A24 Green', price: 19990, description: "ОЗУ: 6 Гб \nПамять: 128 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "36", img: "12.webp", title: 'Samsung Galaxy A05s Lavender', price: 13490, description: "ОЗУ: 4 Гб \nПамять: 64 Гб \nЭкран 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "37", img: "13.webp", title: 'Samsung Galaxy A14 Black', price: 14990, description: "ОЗУ: 4 Гб \nПамять: 128 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "38", img: "14.webp", title: 'Samsung Galaxy A14 Silver', price: 12990, description: "ОЗУ: 4 Гб \nПамять: 64 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "39", img: "15.webp", title: 'Samsung Galaxy A04 White', price: 10990, description: "ОЗУ: 4 Гб \nПамять: 64 Гб \nDual Nano SIM \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "50", img: "16.webp", title: 'Redmi Note 12 Onyx Gray', price: 17990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nПроцессор: MediaTek Helio G96 \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "51", img: "17.webp", title: 'Redmi Note 12 Ice Blue', price: 17990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nПроцессор: MediaTek Helio G96 \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "52", img: "18.webp", title: 'Redmi 12 Midnight Black', price: 12990, description: "ОЗУ: 4 Гб \nПамять: 128 Гб \nЭкран 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "53", img: "19.webp", title: 'Redmi Note 13C Black', price: 13990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nЭкран: 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "54", img: "20.webp", title: 'Realme C67 Black Stone', price: 17990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nПроцессор: Snapdragon 685 \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "55", img: "27.webp", title: 'Redmi Note 13 Pro Midnight', price: 29990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nЭкран: 120 Гц\nБыстрая зарядка 67 Вт\nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "56", img: "28.webp", title: 'Poco C65 Black', price: 13990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nБыстрая зарядка 18 Вт\nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "57", img: "29.webp", title: 'Redmi A2+ Black', price: 5990, description: "ОЗУ: 3 Гб \nПамять: 64 Гб \nПроцессор: MediaTek Helio G36\nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "58", img: "30.webp", title: 'Redmi A3 Midnight Black', price: 7990, description: "ОЗУ: 4 Гб \nПамять: 128 Гб \nЭкран: 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "59", img: "31.webp", title: 'Redmi A3 Lake Blue', price: 7990, description: "ОЗУ: 4 Гб \nПамять: 128 Гб \nЭкран: 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "60", img: "21.webp", title: 'INOI A62', price: 4990, description: "ОЗУ: 4 Гб \nПамять: 64 Гб \nDual Nano SIM \nАккумулятор: 3500 mAh", category: "Телефоны"},
    {id: "70", img: "22.webp", title: 'Infinix Note 30i Obsidian Black', price: 12990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nБыстрая зарядка 33Вт \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "71", img: "23.webp", title: 'Infinix Hot 40i Starlit Black', price: 12990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nБыстрая зарядка 18Вт \nЭкран 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "72", img: "24.webp", title: 'Infinix Hot 40i Palm Blue', price: 12990, description: "ОЗУ: 8 Гб \nПамять: 256 Гб \nБыстрая зарядка 18Вт \nЭкран 90 Гц \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "73", img: "25.webp", title: 'Infinix Note 30i Obsidian Black', price: 9900, description: "ОЗУ: 8 Гб \nПамять: 128 Гб \nБыстрая зарядка 33Вт\nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "74", img: "32.webp", title: 'Infinix Smart 8 Plus', price: 8490, description: "ОЗУ: 4 Гб \nПамять: 128 Гб \nЭкран: 90 Гц\nБыстрая зарядка 18Вт\nАккумулятор: 6000 mAh\nСвязь в подарок", category: "Телефоны"},
    {id: "75", img: "26.webp", title: 'Itel A70 Starlish Black', price: 7490, description: "ОЗУ: 4 Гб \nПамять: 256 Гб \nБыстрая зарядка \nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "76", img: "33.webp", title: 'Itel P55 Aurora Blue', price: 12990, description: "ОЗУ: 8 Гб \nПамять: 128 Гб \nБыстрая зарядка 18Вт\nАккумулятор: 5000 mAh", category: "Телефоны"},
    {id: "77", img: "33.webp", title: 'Itel P55 Aurora Blue', price: 12990, description: "ОЗУ: 8 Гб \nПамять: 128 Гб \nБыстрая зарядка 18Вт\nАккумулятор: 5000 mAh", category: "Телефоны"},
    //...
    {id: "200", img: "100.webp", title: 'AirPods 3 MagSafe', price: 16990, description: "", category: "Наушники"},
    {id: "201", img: "101.webp", title: 'AirPods Pro 2', price: 22990, description: "", category: "Наушники"},
    {id: "202", img: "102.webp", title: 'AirPods 2', price: 11990, description: "", category: "Наушники"},
    {id: "203", img: "103.webp", title: 'Hoco ESD11', price: 1190, description: "", category: "Наушники"},
    {id: "204", img: "104.webp", title: 'Choice HW15', price: 1090, description: "", category: "Наушники"},
    //...
    {id: "300", img: "200.webp", title: 'Яндекс Станция Лайт', price: 4990, description: "", category: "Колонки"},
    {id: "301", img: "201.webp", title: 'Яндекс Станция Лайт', price: 4990, description: "", category: "Колонки"},
    {id: "302", img: "202.webp", title: 'Капсула Мини С Марусей', price: 4990, description: "", category: "Колонки"},
    {id: "303", img: "203.webp", title: 'JBL Go3 Black', price: 3790, description: "", category: "Колонки"},
    {id: "304", img: "204.webp", title: 'Hoco HC17 Bordo', price: 1590, description: "", category: "Колонки"},
]